[package]
name = "rust-polygon-ingestion"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = {version = "0.23.0", features = ["streams"] }

[[bin]]
name = "rust-polygon-ingestion"
path = "src/main.rs"


